CREATE TABLE if NOT EXISTS PERSON (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
birthday VARCHAR(50) NOT NULL,
email VARCHAR (250) NOT NULL,
streetName VARCHAR(250) NOT NULL,
streetNumber INT(10) NOT NULL,
postalCode INT(15) NOT NULL,
city VARCHAR(50) NOT NULL);